openapi: 3.0.1
info:
  title: POSM_API
  description: API Definition of POSM_API
  version: 1.0.0
servers:
- url: http://localhost:8290/posm_api
paths:
  /:
    get:
      responses:
        default:
          description: Default response
