openapi: 3.0.1
info:
  title: Purchase_Return_S1_API
  description: API Definition of Purchase_Return_S1_API
  version: 1.0.0
servers:
- url: http://localhost:8290/purchase_return_s1
paths:
  /{time}:
    get:
      parameters:
      - name: time
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
