openapi: 3.0.1
info:
  title: Purchase_Return_S1_GuaranteedDelivery_API
  description: API Definition of Purchase_Return_S1_GuaranteedDelivery_API
  version: 1.0.0
servers:
- url: http://localhost:8290/purchase_return_s1_guaranteedDelivery
paths:
  /:
    post:
      responses:
        default:
          description: Default response
