openapi: 3.0.1
info:
  title: Sale_Order_Creation
  description: API Definition of Sale_Order_Creation
  version: 1.0.0
servers:
- url: http://localhost:8290/sale_order_creation_s2
paths:
  /:
    get:
      responses:
        default:
          description: Default response
