openapi: 3.0.1
info:
  title: purchase_order_creation_s1_guaranteedDelivery_api
  description: API Definition of purchase_order_creation_s1_guaranteedDelivery_api
  version: 1.0.0
servers:
- url: http://localhost:8290/purchase_order_creation_s1_guaranteedDelivery
paths:
  /:
    post:
      responses:
        default:
          description: Default response
