openapi: 3.0.1
info:
  title: purchase_order_creation_s1
  description: API Definition of purchase_order_creation_s1
  version: 1.0.0
servers:
- url: http://localhost:8290/purchase_order_creation_s1
paths:
  /{time}:
    get:
      parameters:
      - name: time
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
