openapi: 3.0.1
info:
  title: Customer_Invoice_API
  description: API Definition of Customer_Invoice_API
  version: 1.0.0
servers:
- url: http://localhost:8290/customer_invoice
paths:
  /:
    get:
      responses:
        default:
          description: Default response
