openapi: 3.0.1
info:
  title: Customer_Invoice_GuaranteedDelivery_API
  description: API Definition of Customer_Invoice_GuaranteedDelivery_API
  version: 1.0.0
servers:
- url: http://localhost:8290/customer_invoice_guaranteedDelivery
paths:
  /:
    post:
      responses:
        default:
          description: Default response
